avc:  granted  { search } for comm="chrome" name="pulse" dev="dm-0" ino=239510 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=dir
avc:  granted  { read } for comm="chrome" name="pulse" dev="tmpfs" ino=54 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmp_t tclass=dir
avc:  granted  { read } for comm="chrome" path="/run/user/1000/pulse" dev="tmpfs" ino=54 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmp_t tclass=dir
avc:  granted  { search } for comm="threaded-ml" name="pulse" dev="dm-0" ino=239510 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=dir
avc:  granted  { read } for comm="threaded-ml" name="cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { read open } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { use } for comm="pulseaudio" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=4611 scontext=user_u:user_r:pulseaudio_t tcontext=user_u:user_r:chromium_t tclass=fd
avc:  granted  { use } for comm="pulseaudio" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=4611 scontext=user_u:user_r:pulseaudio_t tcontext=user_u:user_r:chromium_t tclass=fd
avc:  granted  { map } for comm="threaded-ml" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=1035 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmpfs_t tclass=file
avc:  granted  { map } for comm="threaded-ml" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=4612 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmpfs_t tclass=file
avc:  granted  { search } for comm="chrome" name="pulse" dev="dm-0" ino=239510 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=dir
avc:  granted  { read } for comm="chrome" name="pulse" dev="tmpfs" ino=54 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmp_t tclass=dir
avc:  granted  { read } for comm="chrome" path="/run/user/1000/pulse" dev="tmpfs" ino=54 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmp_t tclass=dir
avc:  granted  { search } for comm="threaded-ml" name="pulse" dev="dm-0" ino=239510 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=dir
avc:  granted  { read } for comm="threaded-ml" name="cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { read open } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { use } for comm="pulseaudio" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=4613 scontext=user_u:user_r:pulseaudio_t tcontext=user_u:user_r:chromium_t tclass=fd
avc:  granted  { use } for comm="pulseaudio" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=4613 scontext=user_u:user_r:pulseaudio_t tcontext=user_u:user_r:chromium_t tclass=fd
avc:  granted  { map } for comm="threaded-ml" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=1035 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmpfs_t tclass=file
avc:  granted  { map } for comm="threaded-ml" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=4614 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmpfs_t tclass=file
avc:  granted  { search } for comm="chrome" name="pulse" dev="dm-0" ino=239510 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=dir
avc:  granted  { read } for comm="chrome" name="pulse" dev="tmpfs" ino=54 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmp_t tclass=dir
avc:  granted  { read } for comm="chrome" path="/run/user/1000/pulse" dev="tmpfs" ino=54 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmp_t tclass=dir
avc:  granted  { search } for comm="threaded-ml" name="pulse" dev="dm-0" ino=239510 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=dir
avc:  granted  { read } for comm="threaded-ml" name="cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { read open } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { use } for comm="pulseaudio" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=4615 scontext=user_u:user_r:pulseaudio_t tcontext=user_u:user_r:chromium_t tclass=fd
avc:  granted  { use } for comm="pulseaudio" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=4615 scontext=user_u:user_r:pulseaudio_t tcontext=user_u:user_r:chromium_t tclass=fd
avc:  granted  { map } for comm="threaded-ml" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=1035 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmpfs_t tclass=file
avc:  granted  { map } for comm="threaded-ml" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=5521 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmpfs_t tclass=file
avc:  granted  { search } for comm="chrome" name="pulse" dev="dm-0" ino=239510 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=dir
avc:  granted  { read } for comm="chrome" name="pulse" dev="tmpfs" ino=54 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmp_t tclass=dir
avc:  granted  { read } for comm="chrome" path="/run/user/1000/pulse" dev="tmpfs" ino=54 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmp_t tclass=dir
avc:  granted  { search } for comm="threaded-ml" name="pulse" dev="dm-0" ino=239510 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=dir
avc:  granted  { read } for comm="threaded-ml" name="cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { read open } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { map } for comm="threaded-ml" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=1035 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmpfs_t tclass=file
avc:  granted  { use } for comm="pulseaudio" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=4616 scontext=user_u:user_r:pulseaudio_t tcontext=user_u:user_r:chromium_t tclass=fd
avc:  granted  { map } for comm="threaded-ml" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=5522 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmpfs_t tclass=file
avc:  granted  { use } for comm="pulseaudio" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=4616 scontext=user_u:user_r:pulseaudio_t tcontext=user_u:user_r:chromium_t tclass=fd
avc:  granted  { search } for comm="chrome" name="pulse" dev="dm-0" ino=239510 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=dir
avc:  granted  { read } for comm="chrome" name="pulse" dev="tmpfs" ino=54 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmp_t tclass=dir
avc:  granted  { read } for comm="chrome" path="/run/user/1000/pulse" dev="tmpfs" ino=54 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmp_t tclass=dir
avc:  granted  { search } for comm="threaded-ml" name="pulse" dev="dm-0" ino=239510 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=dir
avc:  granted  { read } for comm="threaded-ml" name="cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { read open } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { use } for comm="pulseaudio" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=5523 scontext=user_u:user_r:pulseaudio_t tcontext=user_u:user_r:chromium_t tclass=fd
avc:  granted  { use } for comm="pulseaudio" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=5523 scontext=user_u:user_r:pulseaudio_t tcontext=user_u:user_r:chromium_t tclass=fd
avc:  granted  { map } for comm="threaded-ml" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=1035 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmpfs_t tclass=file
avc:  granted  { map } for comm="threaded-ml" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=5524 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmpfs_t tclass=file
avc:  granted  { search } for comm="chrome" name="pulse" dev="dm-0" ino=239510 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=dir
avc:  granted  { read } for comm="chrome" name="pulse" dev="tmpfs" ino=54 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmp_t tclass=dir
avc:  granted  { read } for comm="chrome" path="/run/user/1000/pulse" dev="tmpfs" ino=54 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmp_t tclass=dir
avc:  granted  { search } for comm="threaded-ml" name="pulse" dev="dm-0" ino=239510 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=dir
avc:  granted  { read } for comm="threaded-ml" name="cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { read open } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { lock } for comm="threaded-ml" path="/home/user/.config/pulse/cookie" dev="dm-0" ino=239511 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_xdg_config_t tclass=file
avc:  granted  { use } for comm="pulseaudio" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=4617 scontext=user_u:user_r:pulseaudio_t tcontext=user_u:user_r:chromium_t tclass=fd
avc:  granted  { use } for comm="pulseaudio" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=4617 scontext=user_u:user_r:pulseaudio_t tcontext=user_u:user_r:chromium_t tclass=fd
avc:  granted  { map } for comm="threaded-ml" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=1035 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmpfs_t tclass=file
avc:  granted  { map } for comm="threaded-ml" path=2F6D656D66643A70756C7365617564696F202864656C6574656429 dev="tmpfs" ino=5525 scontext=user_u:user_r:chromium_t tcontext=user_u:object_r:pulseaudio_tmpfs_t tclass=file
